### ISSUE TITLE
加点新东西

### ISSUE THREAD

**Issue by lss233** [paradox8599/mirai-chatgpt-setup#1]
根据 [这条帖子](https://mirai.mamoe.net/topic/1653/%E5%8D%87%E7%BA%A7-mirai-%E8%87%B3-2-13-2-%E4%BD%BF%E7%94%A8%E6%96%B0%E7%9A%84%E7%9F%AD%E4%BF%A1%E9%AA%8C%E8%AF%81%E6%96%B9%E6%B3%95%E8%A7%A3%E5%86%B3%E8%AE%BE%E5%A4%87%E9%AA%8C%E8%AF%81/1?lang=zh-CN) 的介绍，最新版 Mirai 是支持短信验证登录的，可以提高登录的成功率。  

但是目前使用的 Mirai 镜像还不是最新版，所以体验不了这个功能。不知道这个 repo 能不能弥补这个遗憾？

另外，希望可以加入一些其他方便登录QQ的插件，比如说 [mirai-device-generator](https://github.com/cssxsh/mirai-device-generator) 和验证码的功能。  

非常感谢！

**Comment by paradox8599** [comment]
这个脚本只是把 [原项目](https://github.com/lss233/chatgpt-mirai-qq-bot/) 的配置文件整合了一下，我自己对mirai并不是很了解。
不过我自己在登录的时候是有短信验证的。
今晚我会尝试研究一下mirai的文档，谢谢建议。

**Comment by hackhy2020** [comment]
原作者已经更新了，还可以用吗，我看到刚更新？

**Comment by paradox8599** [comment]
> 原作者已经更新了，还可以用吗，我看到刚更新？

不知道是不是因为我在海外，mcl每次安装都巨慢(~10分钟)，目前实在没什么时间和耐心。

有什么办法加速吗，我试了换其他源，好像并没有什么用。

**Comment by paradox8599** [comment]
已更新。
@hackhy2020
