### ISSUE TITLE
mirai部署成功了，启动docker的时候卡住了

### ISSUE THREAD

**Issue by fangyuan99** [paradox8599/mirai-chatgpt-setup#4]
如图：已测试mirai可以正常自动登陆
![image](https://user-images.githubusercontent.com/62874116/210030748-51d9845f-6877-4e0b-be76-d454d2bfe368.png)

**Comment by fangyuan99** [comment]
![image](https://user-images.githubusercontent.com/62874116/210051089-f593f7d2-fb71-4759-b764-d2754519e527.png)

**Comment by paradox8599** [comment]
看起来好像是 apt 镜像源的问题。
回头我加个国内的源。
不过原项目现在好像也是运行不起来的状态，等等吧。
或者找找其他现在还能用的项目。

**Comment by fangyuan99** [comment]
原作者更新了 ，有个库出了问题

**Comment by paradox8599** [comment]
如果原项目没有改配置文件内容和流程的话，这个项目就一直能用。

**Comment by fangyuan99** [comment]
![image](https://user-images.githubusercontent.com/62874116/210082428-7b2879f1-4fb0-49b9-985c-0e28e1aa696b.png)
报这个错，好像原项目就是修复了这个

**Comment by lss233** [comment]
@paradox8599 Dockerfile 有更新，现在 revChatGPT 又改成了 Chromium 了 。

@fangyuan99 看样子你需要更新下容器里的 revChatGPT

**Comment by fangyuan99** [comment]
> 

`docker pull lss233/chatgpt-mirai-qq-bot:latest`是用这个么，还是一样的错误

**Comment by paradox8599** [comment]
@lss233 Dockerfile 已跟进。

@fangyuan99 这个项目的目的就是把简化繁琐的操作，所以如果不关心更细节的配置，就不用操心原项目的内容，我都已经封装好了。
pull下来后运行 `docker compose build` 就能获得最新版的镜像，我也更新了 README 的相关内容。

> 或者干脆全删了重新 clone，按照 [`README`](https://github.com/paradox8599/mirai-chatgpt-setup#readme) 步骤顺序操作。
